// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bash-service.proto

package bash

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommandRequest struct {
	// Actual command to run
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// User to run as
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// Current working directory
	Cwd                  string   `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandRequest) Reset()         { *m = CommandRequest{} }
func (m *CommandRequest) String() string { return proto.CompactTextString(m) }
func (*CommandRequest) ProtoMessage()    {}
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_769f0d952cf1ab41, []int{0}
}

func (m *CommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandRequest.Unmarshal(m, b)
}
func (m *CommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandRequest.Marshal(b, m, deterministic)
}
func (m *CommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandRequest.Merge(m, src)
}
func (m *CommandRequest) XXX_Size() int {
	return xxx_messageInfo_CommandRequest.Size(m)
}
func (m *CommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandRequest proto.InternalMessageInfo

func (m *CommandRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *CommandRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *CommandRequest) GetCwd() string {
	if m != nil {
		return m.Cwd
	}
	return ""
}

type CommandResponse struct {
	// Standard output
	Stdout string `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Standard error
	Stderr string `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Exit status
	ExitStatus           int32    `protobuf:"varint,3,opt,name=exitStatus,proto3" json:"exitStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandResponse) Reset()         { *m = CommandResponse{} }
func (m *CommandResponse) String() string { return proto.CompactTextString(m) }
func (*CommandResponse) ProtoMessage()    {}
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_769f0d952cf1ab41, []int{1}
}

func (m *CommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandResponse.Unmarshal(m, b)
}
func (m *CommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandResponse.Marshal(b, m, deterministic)
}
func (m *CommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandResponse.Merge(m, src)
}
func (m *CommandResponse) XXX_Size() int {
	return xxx_messageInfo_CommandResponse.Size(m)
}
func (m *CommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommandResponse proto.InternalMessageInfo

func (m *CommandResponse) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *CommandResponse) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func (m *CommandResponse) GetExitStatus() int32 {
	if m != nil {
		return m.ExitStatus
	}
	return 0
}

func init() {
	proto.RegisterType((*CommandRequest)(nil), "bash.CommandRequest")
	proto.RegisterType((*CommandResponse)(nil), "bash.CommandResponse")
}

func init() { proto.RegisterFile("bash-service.proto", fileDescriptor_769f0d952cf1ab41) }

var fileDescriptor_769f0d952cf1ab41 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x8d, 0xad, 0x2d, 0x8e, 0x50, 0x65, 0x50, 0x09, 0x1e, 0x44, 0xf6, 0xe4, 0xc5, 0x45,
	0xf4, 0xe2, 0xb5, 0x8a, 0xf7, 0xb2, 0x7d, 0x82, 0x34, 0x19, 0x68, 0xa1, 0xbb, 0x59, 0x33, 0x13,
	0xdd, 0x67, 0xf0, 0xa9, 0x65, 0xb3, 0x59, 0x51, 0x6f, 0xde, 0xfe, 0xff, 0x83, 0x7c, 0xe4, 0x1f,
	0xc0, 0x8d, 0xe1, 0xed, 0x1d, 0x53, 0x78, 0xdf, 0x59, 0x2a, 0xdb, 0xe0, 0xc5, 0xe3, 0xb4, 0x67,
	0xc5, 0x0a, 0x16, 0x2f, 0xbe, 0xae, 0x4d, 0xe3, 0x2a, 0x7a, 0x8b, 0xc4, 0x82, 0x1a, 0xe6, 0x76,
	0x20, 0x5a, 0xdd, 0xa8, 0xdb, 0xe3, 0x6a, 0xac, 0x88, 0x30, 0x8d, 0x4c, 0x41, 0x1f, 0x26, 0x9c,
	0x32, 0x9e, 0xc1, 0xc4, 0x7e, 0x38, 0x3d, 0x49, 0xa8, 0x8f, 0x85, 0x81, 0xd3, 0x6f, 0x23, 0xb7,
	0xbe, 0x61, 0xc2, 0x4b, 0x98, 0xb1, 0x38, 0x1f, 0x25, 0x1b, 0x73, 0xcb, 0x9c, 0xc2, 0xa8, 0xcc,
	0x0d, 0xaf, 0x01, 0xa8, 0xdb, 0xc9, 0x5a, 0x8c, 0x44, 0x4e, 0xee, 0xa3, 0xea, 0x07, 0x79, 0xf8,
	0x54, 0x70, 0xf2, 0x6c, 0x78, 0xbb, 0x1e, 0x06, 0xe1, 0x13, 0xcc, 0x5f, 0x3b, 0xb2, 0x51, 0x08,
	0xcf, 0xcb, 0x7e, 0x56, 0xf9, 0x7b, 0xd3, 0xd5, 0xc5, 0x1f, 0x3a, 0xfc, 0xab, 0x38, 0xc0, 0x25,
	0x2c, 0xf2, 0xcb, 0x65, 0xe3, 0x56, 0x7e, 0xbf, 0xff, 0xa7, 0xe0, 0x5e, 0x6d, 0x66, 0xe9, 0x9c,
	0x8f, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb5, 0x43, 0x9a, 0x75, 0x64, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BashServiceClient is the client API for BashService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BashServiceClient interface {
	// Run a command
	Execute(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	ExecuteAndPoll(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (BashService_ExecuteAndPollClient, error)
}

type bashServiceClient struct {
	cc *grpc.ClientConn
}

func NewBashServiceClient(cc *grpc.ClientConn) BashServiceClient {
	return &bashServiceClient{cc}
}

func (c *bashServiceClient) Execute(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, "/bash.BashService/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bashServiceClient) ExecuteAndPoll(ctx context.Context, in *CommandRequest, opts ...grpc.CallOption) (BashService_ExecuteAndPollClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BashService_serviceDesc.Streams[0], "/bash.BashService/ExecuteAndPoll", opts...)
	if err != nil {
		return nil, err
	}
	x := &bashServiceExecuteAndPollClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BashService_ExecuteAndPollClient interface {
	Recv() (*CommandResponse, error)
	grpc.ClientStream
}

type bashServiceExecuteAndPollClient struct {
	grpc.ClientStream
}

func (x *bashServiceExecuteAndPollClient) Recv() (*CommandResponse, error) {
	m := new(CommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BashServiceServer is the server API for BashService service.
type BashServiceServer interface {
	// Run a command
	Execute(context.Context, *CommandRequest) (*CommandResponse, error)
	ExecuteAndPoll(*CommandRequest, BashService_ExecuteAndPollServer) error
}

// UnimplementedBashServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBashServiceServer struct {
}

func (*UnimplementedBashServiceServer) Execute(ctx context.Context, req *CommandRequest) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedBashServiceServer) ExecuteAndPoll(req *CommandRequest, srv BashService_ExecuteAndPollServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteAndPoll not implemented")
}

func RegisterBashServiceServer(s *grpc.Server, srv BashServiceServer) {
	s.RegisterService(&_BashService_serviceDesc, srv)
}

func _BashService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BashServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bash.BashService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BashServiceServer).Execute(ctx, req.(*CommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BashService_ExecuteAndPoll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BashServiceServer).ExecuteAndPoll(m, &bashServiceExecuteAndPollServer{stream})
}

type BashService_ExecuteAndPollServer interface {
	Send(*CommandResponse) error
	grpc.ServerStream
}

type bashServiceExecuteAndPollServer struct {
	grpc.ServerStream
}

func (x *bashServiceExecuteAndPollServer) Send(m *CommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _BashService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bash.BashService",
	HandlerType: (*BashServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _BashService_Execute_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteAndPoll",
			Handler:       _BashService_ExecuteAndPoll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bash-service.proto",
}
